#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Find files that appear to be text that contain incorrect EOL sequences
# (e.g. CR, or any combination, instead of LF).

# TODO: have an outer loop that iterates over the various file extensions,
#       rather than having these lines commented out, which is dumb.
#for FILE in `find . -iname "*.properties" -print`; do
#for FILE in `find . -iname "manifest.mf" -print`; do
for FILE in `find . -iname "*.xml" -print`; do
#for FILE in `find . -iname "*.java" -print`; do
#for FILE in `find . -iname "*.form" -print`; do
    od -x $FILE | grep -i "0d" > /dev/null
    if [ $? = 0 ]; then
        echo $FILE
    fi
done
