#!/bin/bash
#
# Shell script to create symbolic links for all files found in a given
# directory. Links are created in the current working directory.
#

if [ -z "$1" ]; then
    echo "Missing required directory argument!"
    exit
fi

DIR=$1

for FILE in `find $DIR -type f -print`; do
    ln -s $FILE
done
