#!/bin/bash
#
# Shell script to remove all unversioned files from client.
#

tempfoo=`basename $0`
TMPFILE=`mktemp -t ${tempfoo}` && {
    cat > $TMPFILE <<-EOF
/^\?/ {
    sub (/^\? +/, "")
    print "\"" \$0 "\""
}
EOF
    svn st | awk -f $TMPFILE | xargs rm -rf
    rm $TMPFILE
}
