#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Find the @author tags in Java code and display the unique set of names.

if [ -z "$1" ]; then
    echo "Missing required path in which to find .java files!"
    exit
fi
# There are tabs in the [ ] below, to capture spaces and tabs for removal.
DIR=$1
find $DIR -name "*.java" -print | xargs grep -ih "@author" | \
sed -e 's/.*@author//' -e 's/^[ 	]*//' -e 's/[ 	]*$//' | \
sort | \
uniq -c
