#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Script that searches jar files for matching expressions.
# Used to find out which .jar file contains a particular class.

if [ -z "$1" ]; then
    echo "Missing required directory argument!"
    exit
fi
if [ -z "$2" ]; then
    echo "Missing required pattern argument!"
    exit
fi
if [ -z "$JAVA_HOME" ]; then
    echo "Missing JAVA_HOME environment variable!"
    exit
fi

DIR=$1
PATTERN=$2

for FILE in `find $DIR -type f \( -name "*.nbm" -o -name "*.?ar" -o -name "*.zip" \) -print`; do
    $JAVA_HOME/bin/jar tf $FILE | grep -i $PATTERN > /dev/null
    if [ $? = 0 ]; then
        echo $FILE
    fi
done
