#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Counts the number of .java files and the total number of lines in them.
# Ignores .svn directories.

COUNT=0
TOTAL=0
for FILE in `find . -name ".svn" -prune -o -name "*.java" -print`; do
    let COUNT++
    SIZE=`cat $FILE | wc -l`
    let TOTAL+=SIZE
done
echo "File count: $COUNT"
echo "Line count: $TOTAL"
