#!/usr/bin/env python
#
# Script to make the output of pylint parseable by pyflakes in Emacs.
# Note that epylint is simply for basic Emacs support, and does not
# output for consumption by pyflakes.
#

import re
import sys
import subprocess

#
# Invoke 'pylint --generate-rcfile' and customize
#
rcfile = "/Users/nfiedler/.pylint"
pylint_args = ["/usr/local/bin/pylint",
               "--rcfile={}".format(rcfile),
               "--output-format=parseable",
               "--reports=no",
               sys.argv[1]]
pylint = subprocess.Popen(pylint_args, stdout = subprocess.PIPE)
stdout = pylint.communicate()[0]

for line in stdout:
    match = re.search("\\[([WE])(, (.+?))?\\]", line)
    if match:
        kind = match.group(1)
        func = match.group(3)
        if kind == "W":
            msg = "Warning"
        else:
            msg = "Error"
        if func:
            line = re.sub("\\[([WE])(, (.+?))?\\]",
                          "%s (%s):" % (msg, func), line)
        else:
            line = re.sub("\\[([WE])?\\]", "%s:" % msg, line)
    print line,
